In [1]:
from pathlib import Path
import json
import pandas as pd

PROJECT_ROOT = Path.cwd().parent

In [2]:
annotation_path = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "fashionpedia"
    / "annotations"
    / "instances_attributes_val2020.json"
)

with open(annotation_path, "r") as f:
    data = json.load(f)

print(type(data))
print(data.keys())

<class 'dict'>
dict_keys(['info', 'categories', 'attributes', 'licenses', 'annotations', 'images'])

In [3]:
print("Images      :", len(data["images"]))
print("Annotations :", len(data["annotations"]))
print("Categories  :", len(data["categories"]))
print("Attributes  :", len(data["attributes"]))

Images      : 1158
Annotations : 8781
Categories  : 46
Attributes  : 294

In [4]:
categories = pd.DataFrame(data["categories"])

categories.head()

   id                      name supercategory  level   taxonomy_id
0   0             shirt, blouse     upperbody      2   combo000000
1   1  top, t-shirt, sweatshirt     upperbody      2   combo000001
2   2                   sweater     upperbody      2  obj000008_00
3   3                  cardigan     upperbody      2  obj000009_00
4   4                    jacket     upperbody      2  obj000010_00

In [5]:
categories

,id,name,supercategory,level,taxonomy_id
0,0,"shirt, blouse",upperbody,2,combo000000
1,1,"top, t-shirt, sweatshirt",upperbody,2,combo000001
2,2,sweater,upperbody,2,obj000008_00
3,3,cardigan,upperbody,2,obj000009_00
4,4,jacket,upperbody,2,obj000010_00
5,5,vest,upperbody,2,obj000011_00
6,6,pants,lowerbody,2,obj000013_00
7,7,shorts,lowerbody,2,obj000014_00
8,8,skirt,lowerbody,2,obj000015_00
9,9,coat,wholebody,2,obj000017_00
10,10,dress,wholebody,2,obj000018_00
11,11,jumpsuit,wholebody,2,obj000019_00
12,12,cape,wholebody,2,obj000020_00
13,13,glasses,head,2,obj000023_00
14,14,hat,head,2,obj000025_00
15,15,"headband, head covering, hair accessory",head,2,combo000002
16,16,tie,neck,2,obj000030_00
17,17,glove,arms and hands,2,obj000032_00
18,18,watch,arms and hands,2,obj000033_00
19,19,belt,waist,2,obj000035_00
20,20,leg warmer,legs and feet,2,obj000037_00
21,21,"tights, stockings",legs and feet,2,combo000003
22,22,sock,legs and feet,2,obj000040_00
23,23,shoe,legs and feet,2,obj000041_00
24,24,"bag, wallet",others,2,combo000004
25,25,scarf,others,2,obj000045_00
26,26,umbrella,others,2,obj000046_00
27,27,hood,garment parts,2,obj000049_00
28,28,collar,garment parts,2,obj000050_00
29,29,lapel,garment parts,2,obj000051_00
30,30,epaulette,garment parts,2,obj000052_00
31,31,sleeve,garment parts,2,obj000053_00
32,32,pocket,garment parts,2,obj000055_00
33,33,neckline,garment parts,2,obj000056_00
34,34,buckle,closures,2,obj000058_00
35,35,zipper,closures,2,obj000059_00
36,36,applique,decorations,2,obj000061_00
37,37,bead,decorations,2,obj000062_00
38,38,bow,decorations,2,obj000063_00
39,39,flower,decorations,2,obj000064_00
40,40,fringe,decorations,2,obj000065_00
41,41,ribbon,decorations,2,obj000066_00
42,42,rivet,decorations,2,obj000067_00
43,43,ruffle,decorations,2,obj000068_00
44,44,sequin,decorations,2,obj000069_00
45,45,tassel,decorations,2,obj000070_00

In [6]:
attributes = pd.DataFrame(data["attributes"])

attributes.head()

   id               name supercategory  level   taxonomy_id
0   0  classic (t-shirt)      nickname      1  att000002_00
1   1       polo (shirt)      nickname      1  att000003_00
2   2         undershirt      nickname      1  att000004_00
3   3     henley (shirt)      nickname      1  att000005_00
4   4   ringer (t-shirt)      nickname      1  att000006_00

In [7]:
attributes

      id               name    supercategory  level   taxonomy_id
0      0  classic (t-shirt)         nickname      1  att000002_00
1      1       polo (shirt)         nickname      1  att000003_00
2      2         undershirt         nickname      1  att000004_00
3      3     henley (shirt)         nickname      1  att000005_00
4      4   ringer (t-shirt)         nickname      1  att000006_00
..   ...                ...              ...    ...           ...
289  336            peacock           animal      2  att000359_00
290  337              zebra           animal      2  att000360_00
291  338            giraffe           animal      2  att000361_00
292  339      toile de jouy  textile pattern      1  att000362_00
293  340              plant  textile pattern      1  att000363_00

[294 rows x 5 columns]

In [8]:
data["annotations"][0]

{'image_id': 17039,
 'category_id': 31,
 'attribute_ids': [160, 204],
 'segmentation': [[434,
   650,
   428,
   649,
   426,
   642,
   419,
   636,
   412,
   627,
   406,
   617,
   397,
   603,
   393,
   589,
   391,
   576,
   392,
   556,
   398,
   536,
   405,
   518,
   415,
   491,
   419,
   482,
   423,
   472,
   427,
   465,
   435,
   460,
   434,
   465,
   435,
   474,
   441,
   485,
   444,
   494,
   446,
   506,
   448,
   522,
   450,
   533,
   445,
   548,
   444,
   569,
   439,
   575,
   441,
   579,
   441,
   586,
   445,
   592,
   448,
   595,
   466,
   618,
   460,
   624,
   451,
   633,
   445,
   639,
   444,
   638,
   442,
   648,
   443,
   653,
   437,
   652]],
 'bbox': [391.0, 460.0, 75.0, 193.0],
 'area': 7657,
 'iscrowd': 0,
 'id': 0}

In [9]:
category_lookup = {
    c["id"]: c["name"]
    for c in data["categories"]
}

attribute_lookup = {
    a["id"]: a["name"]
    for a in data["attributes"]
}

In [10]:
ann = data["annotations"][0]

print("Category:")
print(category_lookup[ann["category_id"]])

print()

print("Attributes:")

for attr in ann["attribute_ids"]:
    print(attribute_lookup[attr])

Category:
sleeve

Attributes:
wrist-length
set-in sleeve

In [11]:
data.keys()

dict_keys(['info', 'categories', 'attributes', 'licenses', 'annotations', 'images'])